# COLORS

_COLOR_END="\e[m"
_COLOR_RED="\e[31;1m"
_COLOR_GREEN="\e[32;1m"
_COLOR_YELLOW="\e[33;1m"
_COLOR_BLUE="\e[34;1m"
_COLOR_PINK="\e[35;1m"
_COLOR_CYAN="\e[36;1m"
_COLOR_WHITE="\e[37;1m"

# THEMES

_THEME_ERROR="$_COLOR_RED"
_THEME_WARNING="$_COLOR_CYAN"
_THEME_MESSAGE="$_COLOR_GREEN"

