# include code errors

_ERROR_UNEXPECTED=60
_ERROR_ROOT_NOT_ALLOWED=61
_ERROR_INCLUDE=62
_ERROR_EXTGLOB=63
_ERROR_INVALID_ARGUMENT=64
_ERROR_INVALID_DISTRO=65
_ERROR_INSTALL_DEPENDES=66
_ERROR_INSTALL_MAKE_DEPENDES=67
_ERROR_UPDATES=68

